### ISSUE TITLE
Way to many packages and depends needed

### ISSUE THREAD

**Issue by chrisaberson** [chrisaberson/pwr2ppl#2]
There are too many depends. Takes forever to install the package. 

Some fixes - remove tidyverse, replace with dplyr and tidyr. 

Q: Is it possible to import depends that require only one command from a package?

**Comment by Lakens** [comment]
If you need only one command, just take that code, and add it to the function you are creating. Instead of loading an entire package when you only need 1 function, you can just load that one function. Check the license of the original code if you can take the code, and how to attribute it to someone else.
